### ISSUE TITLE
Blockchain

### ISSUE THREAD

**Issue by veerakishorerk** [rjayaswal/Feedback-blockchain#1]
Hi Jayaswal,

Good app.But when i run ./build.sh in BlockChain project and giving me the error.

www doesn't exist

npm info lifecycle blockchain-for-gov-feedback@2.1.0~build:server: Failed to exec build:server script
npm ERR! Linux 4.9.60-linuxkit-aufs
npm ERR! argv "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/bin/npm-cli.js" "run" "build:server"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! blockchain-for-gov-feedback@2.1.0 build:server: `babel www -d bin webpack.config.prod.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the blockchain-for-gov-feedback@2.1.0 build:server script 'babel www -d bin webpack.config.prod.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the blockchain-for-gov-feedback package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel www -d bin webpack.config.prod.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs blockchain-for-gov-feedback
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls blockchain-for-gov-feedback
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /app/npm-debug.log
ERROR: "build:server" exited with 1.

npm info lifecycle blockchain-for-gov-feedback@2.1.0~build: Failed to exec build script
npm ERR! Linux 4.9.60-linuxkit-aufs
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! blockchain-for-gov-feedback@2.1.0 build: `npm-run-all build:webpack build:server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the blockchain-for-gov-feedback@2.1.0 build script 'npm-run-all build:webpack build:server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the blockchain-for-gov-feedback package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm-run-all build:webpack build:server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs blockchain-for-gov-feedback
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls blockchain-for-gov-feedback
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /app/npm-debug.log
The command '/bin/sh -c apt update && apt install -y build-essential       && npm i && npm i --only=dev       && npm run build       && npm prune && apt remove -y build-essential' returned a non-zero code: 1
Pulling reviewer-ca (reviewer-ca:latest)...
ERROR: pull access denied for reviewer-ca, repository does not exist or may require 'docker login'

Thanks
Veera

**Comment by rjayaswal** [comment]
You need to probably setup docker with admin access by default to run this script. Also, you may try running all command individually one at a time to proceed successfully.
