### ISSUE TITLE
Hyperledger

### ISSUE THREAD

**Issue by veerakishorerk** [rjayaswal/Feedback-blockchain#2]
Hi,

There is no integration with client to Hyperledger blockchain network.

Thanks
Veera

**Comment by rjayaswal** [comment]
You need to start node.js server present in BlockChain directory and not in FeedbackServer directory. 
Some minor modification may be needed depending upon your set-up. For more details, you can read the documentation provided by IMB Hyperledger.

**Comment by veerakishorerk** [comment]
Thanks jayaswal.
